<template>
    <div id="login-main">
        <div id="login-title">
            登录
        </div>
        <div id="login-content">
            <div id="login-error-message">
                <span class="error-message"></span>
            </div>
            <div id="login-input">
                <el-input><el-input>
            <div>
            <div id="login-input">
                <el-input><el-input>
            </div>
            <div id="login-forget-password">

            </div>
        </div>
    </div>
</template>

<style lang="scss" scoped>
    @import url();
</style>